import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "media-import",
        invalidates: ["media-decode", "preview-composite", "png-export"],
        targets: ["source.image", "font.embed"],
      },
      {
        interaction: "control-drag",
        invalidates: ["preview-composite"],
        mustNotInvalidate: ["media-decode"],
        targets: ["image.scale", "image.position", "card.radius", "card.shadow"],
      },
      {
        interaction: "control-change",
        invalidates: ["preview-composite"],
        mustNotInvalidate: ["media-decode"],
        targets: [
          "canvas.aspectRatio",
          "canvas.size.width",
          "canvas.size.height",
          "title.text",
          "title.style",
          "caption.text",
          "caption.style",
          "export.includeBackground",
          "appearance.background",
          "export.image.format",
          "export.image.resolution",
        ],
      },
      {
        interaction: "export",
        invalidates: ["png-export"],
        targets: ["export.actions", "export.image.resolution", "export.includeBackground"],
      },
    ],
    passes: [
      {
        cacheKey: ["source.image"],
        id: "media-decode",
        inputs: ["source.image"],
        invalidatedBy: ["source.image", "font.embed"],
        kind: "decode",
        output: "source",
        quality: "full",
        runsOn: "main",
      },
      {
        id: "preview-composite",
        inputs: [
          "source.image",
          "font.embed",
          "canvas.size.width",
          "canvas.size.height",
          "card.radius",
          "card.shadow",
          "image.scale",
          "image.position",
          "title.text",
          "title.style",
          "caption.text",
          "caption.style",
          "export.includeBackground",
          "appearance.background",
        ],
        invalidatedBy: [
          "source.image",
          "font.embed",
          "canvas.size.width",
          "canvas.size.height",
          "card.radius",
          "card.shadow",
          "image.scale",
          "image.position",
          "title.text",
          "title.style",
          "caption.text",
          "caption.style",
          "export.includeBackground",
          "appearance.background",
        ],
        kind: "composite",
        output: "preview",
        quality: "preview",
        runsOn: "main",
      },
      {
        id: "png-export",
        inputs: [
          "source.image",
          "font.embed",
          "canvas.size.width",
          "canvas.size.height",
          "card.radius",
          "image.scale",
          "image.position",
          "title.text",
          "title.style",
          "caption.text",
          "caption.style",
          "export.includeBackground",
          "appearance.background",
          "export.image.resolution",
        ],
        invalidatedBy: [
          "source.image",
          "font.embed",
          "canvas.size.width",
          "canvas.size.height",
          "card.radius",
          "image.scale",
          "image.position",
          "title.text",
          "title.style",
          "caption.text",
          "caption.style",
          "export.includeBackground",
          "appearance.background",
          "export.image.resolution",
        ],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "main",
      },
    ],
  },
  rendererStrategy: "dom",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "PNG export uses Canvas 2D text drawing, so browser font fallback can differ slightly from DOM preview if the selected font is unavailable to canvas.",
    ],
    layers: [
      {
        content: ["bitmap-media", "composite"],
        exportMode: "composited",
        id: "image-card-background",
        kind: "background",
        primitiveCount: "low",
        renderer: "dom",
        uiSelector: "[data-product-output='image-card']",
      },
      {
        content: ["text"],
        exportMode: "composited",
        id: "image-card-text",
        kind: "product-foreground",
        primitiveCount: "low",
        renderer: "dom",
        uiSelector: "[data-product-title='true'], [data-product-caption='true']",
      },
      {
        content: ["composite", "text", "bitmap-media"],
        exportMode: "included",
        id: "image-card-png-export",
        kind: "export-composite",
        primitiveCount: "low",
        renderer: "canvas-2d",
      },
    ],
    performanceRisks: [
      "8K export can create a large canvas; export is isolated to the footer action instead of running during preview interactions.",
    ],
    previewExportDifferenceReason:
      "Preview is DOM for crisp editable text and simple layout; export composites the same state into Canvas 2D to produce PNG bytes.",
    previewRenderer: "dom",
    productRepresentation: "mixed",
    rendererStrategy: "dom",
    rendererWorkload: "simple-composition",
    sourceRepresentation: "image-media",
    whyNotAlternativeStrategies: [
      "SVG would not simplify bitmap media cover/crop behavior.",
      "WebGL/WebGPU are unnecessary for one uploaded image, two text blocks, and lightweight CSS transforms.",
      "Canvas 2D for live preview would reduce native text fidelity without improving this low-primitive workload.",
    ],
  },
  rendererWorkload: "simple-composition",
  scenarios: [
    {
      automated: true,
      automatedTestName: "appPerformance covers source image media import",
      browser: true,
      browserTestName: "image card browser perf: media import preview remains responsive",
      budget: {
        maxInteractionMs: 1200,
        maxLongTaskMs: 200,
        maxPreviewMs: 900,
      },
      expectedObservable:
        "A 4K-class uploaded image appears in the product card without canvas viewport jumps.",
      fixture: "3840x2160 source image imported through fileDrop.",
      id: "source-image-import",
      interaction: "media-import",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 2160, width: 3840 },
          metric: "media-area",
          smoothTarget: { height: 2160, width: 3840 },
          smoothTargetRatio: 1,
          target: "source.image",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "A 4K landscape upload is the heaviest useful source image expected for an SNS card editor.",
        value: { height: 2160, width: 3840 },
      },
      target: "source.image",
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "appPerformance covers live image scale dragging",
      browser: true,
      browserTestName: "image card browser perf: image scale drag stays live",
      budget: {
        maxFrameGapMs: 80,
        maxInteractionMs: 600,
        maxLongTaskMs: 120,
      },
      controlLabel: "Scale",
      expectedObservable:
        "Dragging Scale at the media workload target updates the image crop live.",
      fixture: "4K media workload with Scale dragged to 2.",
      id: "image-scale-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 2,
          metric: "numeric-max",
          smoothTarget: 2,
          smoothTargetRatio: 1,
          target: "image.scale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Scale 2 is the exposed maximum image zoom.",
        value: 2,
      },
      target: "image.scale",
      workload: false,
      workloadFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 2160, width: 3840 },
          metric: "media-area",
          smoothTarget: { height: 2160, width: 3840 },
          smoothTargetRatio: 1,
          target: "source.image",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Scale dragging should be responsive with the largest guaranteed source image.",
        value: { height: 2160, width: 3840 },
      },
      values: {
        default: 1,
        max: 2,
        min: 0.6,
      },
    },
    {
      automated: true,
      automatedTestName: "appPerformance covers PNG export resolution workload",
      browser: true,
      browserTestName: "image card browser perf: 8K PNG export completes within budget",
      budget: {
        maxExportMs: 8000,
        maxLongTaskMs: 250,
      },
      expectedObservable:
        "Export PNG at 8K produces a decoded PNG with the expected long-edge dimension.",
      fixture: "Default card with 8K image export resolution selected.",
      id: "png-export-8k",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "8k",
          metric: "custom",
          smoothTarget: "8k",
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K is the largest exposed PNG export resolution.",
        value: "8k",
      },
      target: "export.image.resolution",
      workload: true,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: ["source.image", "image.scale", "export.image.resolution"],
});
